name: 'terraform validation'

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-validate:
    name: 'check config for terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.7.3'

      - name: Init
        run: terraform init

      - name: validation
        run: terraform validate
